# fly.toml app configuration file generated for varanda-lock on 2024-01-22T17:25:50+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wslah-auth"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
